#pragma once
#include <algorithm>
#include <array>
#include <bit>
#include <catch2/catch_test_macros.hpp>
#include <csignal>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <map>
#include <memory>
#include <string>
#include <sys/mman.h>
#include <sys/wait.h>
#include <tuple>
#include <unistd.h>
#include <vector>
#include "aarch64/disasm-aarch64.h"
#include "runtime/ir/hir_builder.h"
#include "runtime/ir/ir_meta.h"
#include "runtime/ir/opts/cfg_analysis_pass.h"
#include "runtime/ir/opts/const_folding_pass.h"
#include "runtime/ir/opts/deadcode_elimination_pass.h"
#include "runtime/ir/opts/flags_elimination_pass.h"
#include "runtime/ir/opts/loop_invariant_hoist_pass.h"
#include "runtime/ir/opts/reid_instr_pass.h"
#include "runtime/ir/opts/register_alloc_pass.h"
#include "runtime/ir/opts/uniform_elimination_pass.h"
#include "runtime/ir/opts/uniform_store_sink_pass.h"
#include "runtime/backend/mem_map.h"
#include "runtime/backend/address_space.h"
#include "runtime/backend/code_serial.h"
#include "runtime/backend/interp/interpreter.h"
#include "runtime/backend/runtime.h"
#include "runtime/backend/smc_tracker.h"
#include "runtime/backend/arm64/fpcr_mode.h"
#include "runtime/backend/arm64/pshufd_direct.h"
#include "runtime/backend/arm64/trampolines.h"
#include "runtime/backend/arm64/jit/jit_context.h"
#include "runtime/backend/arm64/jit/translator.h"
#include "runtime/common/hot_coalesce_prof.h"
#include "runtime/common/backedge_control.h"
#include "runtime/common/svm_config.h"
#include "runtime/frontend/x86/decoder.h"
#include "runtime/frontend/x86/sse42str_helper.h"
#include "runtime/frontend/x86/x87.h"
#include "compiler/slang/slang.h"
#include "assembler_riscv64.h"
#include "fmt/format.h"
#include "translator/linux/guest_memory.h"
#include "translator/linux/module_features.h"
#include "translator/x86/translator.h"

#include "register_alloc_test_support.h"
using swift::runtime::FeatureSet;
