// ===========================================================================
// BMI1 / BMI2 reference generator -- executes the real encodings on x86-64
// hardware under Rosetta 2 and prints what the hardware actually produced.
// ===========================================================================
//
// HOW TO REGENERATE (Apple Silicon Mac with Rosetta 2)
//   cd source/tests/fuzz
//   clang -arch x86_64 -O1 -o /tmp/bmiref bmi_rosetta_ref.c
//   arch -x86_64 /tmp/bmiref > bmi_rosetta_ref.inc
//   arch -x86_64 /tmp/bmiref --dump-encodings   # audit against a disassembler
//
// WHY TWO ORACLES
// ---------------
// Rosetta has already been caught mis-implementing VPSLLVQ (32-bit shift-count
// truncation) and XSAVE, so a single green oracle proves nothing.  Every row
// this program prints is independently reproduced by Unicorn in
// bmi_unicorn_check.c, and the two tables are diffed before either is trusted.
// Where they disagree the Intel SDM decides.  NOTHING HERE IS HAND-COMPUTED.
//
// WHAT EACH STUB DOES
//     push/save the callee-saved registers; r13 = the data block (arg 0)
//     mov  <11 registers>, [r13+DATA_IN+i*8]      ; seeded and poisoned inputs
//     <INSN>                                       ; the instruction under test
//     setc/seto/setz/sets/setp byte [r13+DATA_FL]  ; the five testable flags
//     mov  [r13+DATA_OUT+i*8], <11 registers>      ; everything read back
//     restore; ret
//
// Flags are captured with SETcc rather than PUSHFQ so the reference does not
// depend on the emulator's PUSHFQ, and so each flag is recorded separately.
// AF is skipped: no SETcc reads it, and every instruction here leaves it
// architecturally undefined anyway.

#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>
#include <signal.h>
#include <setjmp.h>
#include <sys/mman.h>

typedef uint8_t u8;
typedef uint32_t u32;
typedef uint64_t u64;

#include "bmi_shared.h"

// ---------------------------------------------------------------------------
// Runner
// ---------------------------------------------------------------------------
static u8* g_page;
static u8* g_data;
static sigjmp_buf g_jmp;
static volatile int g_trapped;

static void on_sigill(int sig) {
    (void)sig;
    g_trapped = 1;
    siglongjmp(g_jmp, 1);
}

static int run_stub(const Buf* c) {
    if (mprotect(g_page, 4096, PROT_READ | PROT_WRITE) != 0) {
        perror("mprotect rw");
        exit(1);
    }
    memcpy(g_page, c->b, (size_t)c->n);
    if (mprotect(g_page, 4096, PROT_READ | PROT_EXEC) != 0) {
        perror("mprotect rx");
        exit(1);
    }
    g_trapped = 0;
    if (sigsetjmp(g_jmp, 1) == 0) {
        ((void (*)(void*))(void*)g_page)(g_data);
    }
    return !g_trapped;
}

int main(int argc, char** argv) {
    const int dump = argc > 1 && strcmp(argv[1], "--dump-encodings") == 0;
    signal(SIGILL, on_sigill);
    signal(SIGSEGV, on_sigill);
    signal(SIGBUS, on_sigill);
    g_page = mmap(NULL, 4096, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANON, -1, 0);
    g_data = mmap(NULL, 8192, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANON, -1, 0);
    if (g_page == MAP_FAILED || g_data == MAP_FAILED) {
        perror("mmap");
        return 1;
    }

    if (!dump) {
        printf("// GENERATED by bmi_rosetta_ref.c -- do not edit.\n");
        printf("// Every row is what x86-64 hardware produced under Rosetta 2.\n");
        printf("// Fields: name, width, variant (0=reg 1=mem 2=high regs), pair,\n");
        printf("//         dst, dst2 (MULX low half), CF, OF, ZF, SF, PF, others_clean\n");
        printf("static const BmiRef kBmiRefs[] = {\n");
    }

    int skipped = 0, rows = 0;
    for (int oi = 0; oi < NOPS; ++oi) {
        const Op* o = &g_ops[oi];
        for (int w = 0; w < 2; ++w) {
            for (int variant = 0; variant < 3; ++variant) {
                Assign a = assign_for(o->shape, variant);
                if (dump) {
                    Buf ins;
                    ins.n = 0;
                    emit_insn(&ins, o, w, &a);
                    printf("%-8s w%d v%d :", o->name, w, variant);
                    for (int i = 0; i < ins.n; ++i) {
                        printf(" %02x", ins.b[i]);
                    }
                    printf("\n");
                    continue;
                }
                Buf c;
                build_stub(&c, o, w, &a);
                for (int pi = 0; pi < NPAIRS; ++pi) {
                    u64* d = (u64*)g_data;
                    memset(g_data, 0, DATA_SIZE);
                    d[DATA_M / 8] = g_pairs[pi].b;
                    for (int i = 0; i < NREG; ++i) {
                        d[DATA_IN / 8 + i] = seed_for(REG_ORDER[i], &g_pairs[pi]);
                    }
                    if (!run_stub(&c)) {
                        if (skipped++ < 8) {
                            fprintf(stderr, "SKIP %s w%d v%d %s: trapped\n", o->name, w,
                                    variant, g_pairs[pi].name);
                        }
                        continue;
                    }
                    const u8* fl = g_data + DATA_FL;
                    int clean = 1;
                    u64 dst_v = 0, dst2_v = 0;
                    for (int i = 0; i < NREG; ++i) {
                        const int r = REG_ORDER[i];
                        const u64 got = d[DATA_OUT / 8 + i];
                        if (r == a.dst) {
                            dst_v = got;
                        } else if (r == a.dst2) {
                            dst2_v = got;
                        } else if (got != seed_for(r, &g_pairs[pi])) {
                            clean = 0;
                        }
                    }
                    printf("    {\"%s\", %d, %d, \"%s\", 0x%016llxull, 0x%016llxull, %d, %d, "
                           "%d, %d, %d, %d},\n",
                           o->name, w ? 64 : 32, variant, g_pairs[pi].name,
                           (unsigned long long)dst_v, (unsigned long long)dst2_v, fl[0] & 1,
                           fl[1] & 1, fl[2] & 1, fl[3] & 1, fl[4] & 1, clean);
                    ++rows;
                }
            }
        }
    }
    if (!dump) {
        printf("};\n");
        fprintf(stderr, "rows=%d skipped=%d\n", rows, skipped);
    }
    return 0;
}
