#!/usr/bin/env python3
"""Report declared RV64 lowering coverage; execution tests validate shapes.

The opcode list always comes from ir.inc. An interpreter fallback, partial
scalar-only data operation, or rejected allocator opcode cannot satisfy the
--require-native gate. This report alone is not a semantic/performance proof.
"""

import argparse
import json
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
JIT = ROOT / "source/runtime/backend/riscv64/jit"
GENERIC_DATA = {
    "LoadLocal", "StoreLocal", "LoadUniform", "StoreUniform", "LoadMemory", "StoreMemory",
    "LoadMemoryTSO", "StoreMemoryTSO", "Zero", "LoadImm", "BitCast", "GetResult", "Select",
    "SelectZero", "CondSelect",
}
CONTROL = {"Goto", "NotGoto", "BindLabel"}


def emitter_cases():
    result = {}
    declarations = set(re.findall(r"\b(Emit\w+)\(", (JIT / "translator.h").read_text()))
    runtime_sources = (ROOT / "source/runtime/CMakeLists.txt").read_text()
    # Strip comments and strings so braces and "case" examples cannot alter
    # the method boundaries. Only actual Emit* methods are counted.
    for path in sorted(JIT.glob("translator*.cpp")):
        if f"backend/riscv64/jit/{path.name}" not in runtime_sources:
            continue
        source = re.sub(r'//[^\n]*|/\*.*?\*/|"(?:\\.|[^"\\])*"', "", path.read_text(), flags=re.S)
        for match in re.finditer(r"(?:bool|void)\s+JitTranslator::(Emit\w+)\([^)]*\)\s*\{", source):
            method = match.group(1)
            if method not in declarations or method in {"EmitHelper", "EmitTerminal"}:
                continue
            depth, end = 1, match.end()
            while depth and end < len(source):
                depth += (source[end] == "{") - (source[end] == "}")
                end += 1
            if depth:
                raise ValueError(f"unbalanced emitter method {path}:{method}")
            for opcode in re.findall(r"case\s+O::(\w+)\s*:", source[match.end():end]):
                result.setdefault(opcode, set()).add(method)
    return result


def coverage():
    signatures = re.findall(r"^INST\((\w+),\s*([^\n]+)\)", (ROOT / "source/runtime/ir/ir.inc").read_text(), re.M)
    names = [name for name, _ in signatures]
    if len(names) != len(set(names)):
        raise ValueError("duplicate IR opcode")
    native = emitter_cases()
    if extra := set(native) - set(names):
        raise ValueError(f"emitters reference unknown IR: {sorted(extra)}")
    rows = []
    for name, signature in signatures:
        methods = sorted(native.get(name, ()))
        if name in CONTROL:
            status = "native_control"
        elif not methods:
            status = "interpreter_helper"
        elif name in GENERIC_DATA and not any("Vector" in method for method in methods):
            status = "partial_scalar"
        else:
            status = "native"
        rows.append({"opcode": name, "signature": signature, "status": status, "emitters": methods})
    return rows


def markdown(rows):
    counts = {kind: sum(row["status"] == kind for row in rows) for kind in sorted({row["status"] for row in rows})}
    lines = ["# RV64 IR lowering coverage", "", "<!-- Generated by tools/check_riscv_ir_coverage.py --markdown -->", "",
             f"`ir.inc` declares {len(rows)} opcodes. Declared lowering counts: " +
             ", ".join(f"{kind}={count}" for kind, count in counts.items()) + ".", "",
             "This is an implementation inventory. A declared emitter still needs execution tests for its types,",
             "immediates, exceptional cases, extension profiles and instruction budgets. Interpreter fallback",
             "does not count as native performance coverage. `partial_scalar` means vector data shapes still fall back.", "",
             "Host-register operations require Config uniform bindings; register IDs are logical names, not raw RV64 registers.",
             "Local phis are lowered on incoming CFG edges using parallel copies. Cross-block SSA and V256 remain outside",
             "the current block/128-bit execution protocol; the compiler rejects those shapes explicitly.", "",
             "Run `python3 tools/check_riscv_ir_coverage.py --require-native` to check the completion gate.", "",
             "| IR | Signature | Lowering | Emitter |", "| --- | --- | --- | --- |"]
    for row in rows:
        lines.append(f"| {row['opcode']} | {row['signature']} | {row['status']} | {', '.join(row['emitters']) or '—'} |")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--require-native", action="store_true")
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--markdown", action="store_true")
    parser.add_argument("--check-document", action="store_true")
    args = parser.parse_args()
    rows = coverage()
    document = markdown(rows)
    if args.check_document and (ROOT / "docs/riscv64-ir-coverage.md").read_text() != document:
        raise SystemExit("RV64 coverage document is stale")
    if args.json:
        print(json.dumps(rows, indent=2))
    elif args.markdown:
        print(document, end="")
    else:
        print(f"IR opcodes: {len(rows)}")
        for kind in sorted({row["status"] for row in rows}):
            print(f"{kind}: {sum(row['status'] == kind for row in rows)}")
    if args.require_native and any(row["status"] in {"interpreter_helper", "partial_scalar", "rejected"} for row in rows):
        raise SystemExit(1)


if __name__ == "__main__":
    main()
