name: Build and Test

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        cpu_detection: [0, 1]
      fail-fast: false

    runs-on: ${{matrix.os}}

    steps:

    - name: Install build dependencies
      if: ${{matrix.os == 'ubuntu-latest'}}
      run: sudo apt-get install llvm ninja-build

    - name: Install build dependencies
      if: ${{matrix.os == 'macos-latest'}}
      run: |
        brew install llvm ninja
        echo "/usr/local/opt/llvm/bin" >> $GITHUB_PATH

    - name: Checkout biscuit repo
      uses: actions/checkout@v2

    - name: Configure CMake
      run: >
        cmake 
        -B ${{github.workspace}}/build
        -G Ninja

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: ninja

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --extra-verbose -C ${{env.BUILD_TYPE}}
